services:
  machine-learning:
    container_name: machine-learning
    image: haphihung55/machine-learning:latest
    build: .
    ports:
      - 8888:8888
    volumes:
      - ${ML_WORK_DIR:-./work}:/tf/work
